stages:
  - test

test-job:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest --maxfail=1 --disable-warnings --verbose --junitxml=pytest-report.xml
  artifacts:
    paths:
      - pytest-report.xml
    expire_in: 1 week
  reports:
    junit: pytest-report.xml