name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # checkout code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    # setup python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

    # install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

    # run tests
      - name: Run tests with pytest
        run: |
          pytest -q medimatch/Tests/test_code.py


